### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by webzi** [TimIsOverpowered/archive#10]
Hi!

Can you do a readme for this tool?

Looks nice, but I really can't make it work

**Comment by TimIsOverpowered** [comment]
You would need to make your own configs using the templates in https://github.com/TimIsOverpowered/archive/tree/main/config

config.json
default.json
production.json (if used in production mode of nodejs)

That's all you need to make it work for this program.

I'll update the readme with this info 👍 

On a side note, there is a lot of work trying to get google oauth tokens and setting youtube videos public because google makes it extremely hard to upload videos using the api..

**Comment by webzi** [comment]
Yeah I already tried that.

Just get this when doing npm start

`# npm start

> archive@0.0.0 start /opt/archive
> node src/

/opt/archive/node_modules/sequelize/lib/sequelize.js:187
      options.dialect = urlParts.protocol.replace(/:$/, '');
                                          ^

TypeError: Cannot read property 'replace' of null
    at new Sequelize (/opt/archive/node_modules/sequelize/lib/sequelize.js:187:43)
    at Function.module.exports (/opt/archive/src/sequelize.js:5:21)
    at Function.configure (/opt/archive/node_modules/@feathersjs/feathers/lib/application.js:59:8)
    at Object.<anonymous> (/opt/archive/src/app.js:47:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! archive@0.0.0 start: `node src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the archive@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-08T19_32_50_950Z-debug.log`

**Comment by TimIsOverpowered** [comment]
That error means you did not finish your config. You do not have a valid connection URI. Refer to this line https://github.com/TimIsOverpowered/archive/blob/main/config/template_default.json#L9

Please refer to https://github.com/TimIsOverpowered/archive/blob/main/README.md as it is now updated.

**Comment by webzi** [comment]
Oh yeah, I was thinking it would just look for localhost.

You lost me at step 3/4 - I have no clue how to add tables and columns, with only JS stuff - Thought there would be a SQL or something to import

**Comment by TimIsOverpowered** [comment]
I could provide that, but that can easily be done manually by looking up the sql commands

https://www.postgresqltutorial.com/postgresql-create-table/
https://www.postgresqltutorial.com/postgresql-add-column/
